// <auto-generated />
using CHEF.Components.Watcher.Spam;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CHEF.Migrations.SpamIgnoreRoles
{
    [DbContext(typeof(SpamFilterContext))]
    [Migration("20260129150256_SpamAttachmentCount")]
    partial class SpamAttachmentCount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CHEF.Components.Watcher.Spam.SpamFilterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionOnSpam")
                        .HasColumnType("integer")
                        .HasColumnName("action_on_spam");

                    b.Property<int>("AttachmentCountForSpam")
                        .HasColumnType("integer")
                        .HasColumnName("attachment_count_for_spam");

                    b.Property<int>("EmbedCountForSpam")
                        .HasColumnType("integer")
                        .HasColumnName("embed_count_for_spam");

                    b.Property<bool>("IncludeMessageContentInLog")
                        .HasColumnType("boolean")
                        .HasColumnName("include_message_content_in_log");

                    b.Property<int>("MessageSecondsGap")
                        .HasColumnType("integer")
                        .HasColumnName("message_seconds_gap");

                    b.Property<int>("MessagesForAction")
                        .HasColumnType("integer")
                        .HasColumnName("messages_for_action");

                    b.Property<decimal>("MuteRoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("mute_role_id");

                    b.HasKey("Id")
                        .HasName("pk_spam_filter_configs");

                    b.ToTable("spam_filter_configs", (string)null);
                });

            modelBuilder.Entity("CHEF.Components.Watcher.Spam.SpamIgnoreRole", b =>
                {
                    b.Property<decimal>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("discord_id");

                    b.HasKey("DiscordId")
                        .HasName("pk_spam_ignore_roles");

                    b.ToTable("spam_ignore_roles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
